// <auto-generated />
using AccountDataModel.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountDataModel.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountDataModel.Models.Entities.Account.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccountId");

                    b.HasIndex("Balance");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 383306,
                            Balance = 1194m
                        },
                        new
                        {
                            AccountId = 907010,
                            Balance = 4722m
                        },
                        new
                        {
                            AccountId = 177202,
                            Balance = 2979m
                        },
                        new
                        {
                            AccountId = 727775,
                            Balance = 3239m
                        },
                        new
                        {
                            AccountId = 425555,
                            Balance = 4008m
                        },
                        new
                        {
                            AccountId = 525527,
                            Balance = 4711m
                        },
                        new
                        {
                            AccountId = 994190,
                            Balance = 2417m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
