// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionDataModel.DatabaseContext;

#nullable disable

namespace TransactionDataModel.Migrations
{
    [DbContext(typeof(BillDbContext))]
    partial class BillDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionDataModel.Models.Entities.Bill.Bill", b =>
                {
                    b.Property<int>("BillType")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.HasKey("BillType");

                    b.HasIndex("Amount");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillType = 20,
                            Amount = 4L
                        },
                        new
                        {
                            BillType = 50,
                            Amount = 4L
                        },
                        new
                        {
                            BillType = 100,
                            Amount = 4L
                        },
                        new
                        {
                            BillType = 200,
                            Amount = 4L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
